"""empty message

Revision ID: d4dee8475387
Revises: 565c3d1e5274
Create Date: 2021-11-21 12:45:36.020830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4dee8475387'
down_revision = '565c3d1e5274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('friend_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('Sign', sa.String(length=255), nullable=True))
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'Sign')
    op.drop_table('friends')
    # ### end Alembic commands ###
