"""empty message

Revision ID: a91a189535c7
Revises: d64c42613023
Create Date: 2021-11-14 13:40:43.282225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a91a189535c7'
down_revision = 'd64c42613023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'B_UID',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'B_UID',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=11),
               nullable=True)
    op.drop_table('friend')
    # ### end Alembic commands ###
