"""empty message

Revision ID: b1c75fd61ff6
Revises: c4b9e38a2859
Create Date: 2021-11-13 19:36:51.234395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c75fd61ff6'
down_revision = 'c4b9e38a2859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('UID', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'UID')
    # ### end Alembic commands ###
