"""empty message

Revision ID: 8af84b009d40
Revises: f545c4dcbdbf
Create Date: 2021-12-09 10:38:11.407121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af84b009d40'
down_revision = 'f545c4dcbdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Day')
    # ### end Alembic commands ###
